name: Build Executable

on: [push, pull_request]

jobs:
  build:
    name: Build Windows Executable
    runs-on: windows-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --force-reinstall -r requirements.txt

      - name: Install pyinstaller
        run: |
          $Env:CL = "/Od"
          $Env:PYINSTALLER_COMPILE_BOOTLOADER = "true"
          python -m pip install --force-reinstall --ignore-installed --no-binary :all: --no-cache pyinstaller@git+https://github.com/pyinstaller/pyinstaller.git@0d562b5
          $Env:CL = ""

      # Add version info file
      - name: Create Version Info
        run: |
          echo "VSVersionInfo(
            ffi=FixedFileInfo(
              filevers=(1, 0, 0, 0),
              prodvers=(1, 0, 0, 0),
              mask=0x3f,
              flags=0x0,
              OS=0x40004,
              fileType=0x1,
              subtype=0x0,
              date=(0, 0)
            ),
            kids=[
              StringFileInfo([
                StringTable(
                  u'040904B0',
                  [StringStruct(u'CompanyName', u'COVAS'),
                  StringStruct(u'FileDescription', u'COVAS Twitch Integration'),
                  StringStruct(u'FileVersion', u'1.0.0'),
                  StringStruct(u'InternalName', u'COVAS_Twitch_Integration'),
                  StringStruct(u'LegalCopyright', u'Copyright (c) 2024'),
                  StringStruct(u'OriginalFilename', u'COVAS_Twitch_Integration.exe'),
                  StringStruct(u'ProductName', u'COVAS Twitch Integration'),
                  StringStruct(u'ProductVersion', u'1.0.0')])
              ]),
              VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
            ]
          )" > version_info.txt

      - name: Create UI Executable
        run: |
          pyinstaller config_manager.py -y --onefile --noconsole --clean `
            --add-data "assets/EDAI_logo.png;assets" `
            --add-data "assets/EDAI_logo_transparent.png;assets" `
            --version-file version_info.txt `
            --uac-admin `
            --name "COVAS_Twitch_Integration"

      - name: Create Bot Executable
        run: |
          pyinstaller twitch.py -y --onefile --console --clean `
            --version-file version_info.txt `
            --uac-admin `
            --name "COVAS_Twitch_Bot"

      - name: Organize files for artifact
        run: |
          mkdir -p bot
          move dist\COVAS_Twitch_Bot.exe bot\
          copy README.md dist\

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: COVAS_Twitch_Integration_v${{ github.sha }}
          path: |
            ./dist/COVAS_Twitch_Integration.exe
            ./dist/README.md
            ./bot